spring.application.name=AI
spring.ai.dashscope= <your-dashscope-api-key>
spring.ai.dashscope.base-url=https://openapi.dashscope.com/v1/services/text-generation/
spring.ai.dashscope.chat.options.model=deepseek-r1:8b
spring.ai.dashscope.model=baichuan-2-pro
server.address=0.0.0.0

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=deepseek-r1:1.5b


